# Фильмы
## 1. Добавить новый фильм
POST http://localhost:3001/films HTTP/1.1
Content-Type: application/json

{
  "title": "Бэтмен: Начало",
  "description": "В детстве юный наследник огромного состояния Брюс Уэйн оказался свидетелем убийства своих родителей, и тогда он решил бороться с преступностью.",
  "genre": "drama",
  "released": 2005,
  "previewVideoLink": "https://yandex.ru/video/preview/12268624301725430597",
  "videoLink": "https://yandex.ru/video/12268624301725430452",
  "starring": [
        "Кристиан Бэйл",
        "Кэти Холмс",
        "Майкл Кейн",
        "Киллиан Мерфи",
        "Том Уилкинсон",
        "Лиам Нисон",
        "Кэн Ватанабэ",
        "Гари Олдман",
        "Морган Фриман",
        "Рутгер Хауэр"
    ],
  "director": "Кристофер Нолан",
  "runTime": 140,
  "user": "646fcb3ec1b2ff1d003aee3d",
  "posterImage": "https://www.kinopoisk.ru/film/47237/posters/",
  "backgroundImage": "https://www.kinopoisk.ru/picture/805318/",
  "backgroundColor": "#BF45CA",
  "isFavorite": true
}

###

## 2. Редактирование фильма

PATCH http://localhost:3001/films/6480e567dbae8b5def49476a HTTP/1.1
Content-Type: application/json

{
  "title": "Темный рыцарь",
  "description": "Проверка",
  "released": 2008
}

###

## 3. Удаление фильма

DELETE http://localhost:3001/films/6480e067aaf0211ececd441d HTTP/1.1

###

## 4. Получить список фильмов
GET http://localhost:3001/films HTTP/1.1
Content-Type: application/json

###

## 5. Получение списка фильмов определённого жанра
GET http://localhost:3001/films/genre/crime?limit=2 HTTP/1.1
Content-Type: application/json

###

## 6. Получение детальной информации по фильму

GET http://localhost:3001/films/646fcb3ec1b2ff1d003aee44 HTTP/1.1
Content-Type: application/json

###

## 7. Получить промо-фильм
GET http://localhost:3001/promo HTTP/1.1
Content-Type: application/json

###
