# Фильмы
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = films
@contentType = application/json
@filmId = 64876bbe9f22d9b8bdb88a5e
@deleteFilmId = 646fcb3ec1b2ff1d003aee44
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJsYWNrSmFja0BwaXNlbS5sb2NhbCIsImlkIjoiNjQ4ZTIyMzM1MTlhZTgwZTJhMzMzM2I2IiwiaWF0IjoxNjg3MDM2NDgzLCJleHAiOjE2ODcyMDkyODN9.0eUNOqfd9M9OTQTsEKWRuq3kvsWUtBryNFQvFIqE7jE
## 1. Добавить новый фильм
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Бэтмен: Начало",
  "description": "В детстве юный наследник огромного состояния Брюс Уэйн оказался свидетелем убийства своих родителей, и тогда он решил бороться с преступностью.",
  "genre": "drama",
  "released": 2005,
  "previewVideoLink": "https://yandex.ru/video/preview/12268624301725430597",
  "videoLink": "https://yandex.ru/video/12268624301725430452",
  "starring": [
        "Кристиан Бэйл",
        "Кэти Холмс",
        "Майкл Кейн",
        "Киллиан Мерфи",
        "Том Уилкинсон",
        "Лиам Нисон",
        "Кэн Ватанабэ",
        "Гари Олдман",
        "Морган Фриман",
        "Рутгер Хауэр"
    ],
  "director": "Кристофер Нолан",
  "runTime": 140,
  "user": "646fcb3ec1b2ff1d003aee3d",
  "posterImage": "https://www.kinopoisk.ru/film/47237/posters/",
  "backgroundImage": "https://www.kinopoisk.ru/picture/805318/",
  "backgroundColor": "#BF45CA",
  "isFavorite": true
}

###

## 2. Редактирование фильма

PATCH {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Темный рыцарь",
  "description": "Проверка новая проверка и еще одна проверка на проверке с проверкой",
  "released": 2008
}

###

## 3. Удаление фильма

DELETE {{host}}/{{parentPath}}/{{deleteFilmId}} HTTP/1.1
Authorization: Bearer {{token}}

###

## 4. Получить список фильмов
GET {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

###

## 5. Получение списка фильмов определённого жанра
GET {{host}}/{{parentPath}}/genre/drama?limit=2 HTTP/1.1
Content-Type: {{contentType}}

###

## 6. Получение детальной информации по фильму

GET {{host}}/{{parentPath}}/{{filmId}} HTTP/1.1
Content-Type: {{contentType}}

###

## 7. Получить промо-фильм
GET {{host}}/promo HTTP/1.1
Content-Type: {{contentType}}

###
