# Комментарии
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = comments
@childrenPath = films
@contentType = application/json
@filmId = 64876bbe9f22d9b8bdb88a5e
@deleteFilmId = 648e2121519ae80e2a3333aa
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJsYWNrSmFja0BwaXNlbS5sb2NhbCIsImlkIjoiNjQ4ZTIyMzM1MTlhZTgwZTJhMzMzM2I2IiwiaWF0IjoxNjg3MDM2NDgzLCJleHAiOjE2ODcyMDkyODN9.0eUNOqfd9M9OTQTsEKWRuq3kvsWUtBryNFQvFIqE7jE

## Создать комментарий
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "text": "Тот момент, когда десяток отрицательный комментариев ближе, чем три сотни положительных.",
  "rating": 7,
  "filmId": "64876bbe9f22d9b8bdb88a5e"
}

###

## Список комментариев к фильму
GET {{host}}/{{childrenPath}}/{{filmId}}/{{parentPath}} HTTP/1.1

###

## Удаление фильма

DELETE {{host}}/{{childrenPath}}/{{deleteFilmId}} HTTP/1.1
Authorization: Bearer {{token}}
