# Пользователи
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@parentPath = users
@contentType = application/json
@userId = 646fcb3ec1b2ff1d003aee3d
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IkJsYWNrSmFja0BwaXNlbS5sb2NhbCIsImlkIjoiNjQ5NzZmMTJhYWFhYTY2M2Q4YzVkY2RiIiwiaWF0IjoxNjg3NjQ2MDY2LCJleHAiOjE2ODc4MTg4NjZ9.TT9IBZqtM7RBeYnJQPoJ5OJS_gxo1sgRmRIaa65-jSA

## Создать нового пользователя

POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "BlackJack@pisem.local",
  "avatar": "BlackJack.png",
  "name": "Jack",
  "password": "qwerty"
}

###


## Авторизовать пользователя

POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "BlackJack@pisem.local",
  "password": "qwerty"
}

###

## Отправка аватарки пользователю

POST {{host}}/{{parentPath}}/{{userId}}/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/jpeg

< C:\Users\Professional\Desktop\dew.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
###

## Проверить токен пользователя
GET {{host}}/{{parentPath}}/login HTTP/1.1
Authorization: Bearer {{token}}

###
